#!/bin/bash
export HISTIGNORE="*resumoSO.sh*"
export HISTCONTROL=ignoreboth:erasedups:ignorespace

COMANDOS=(
    "echo 'RESUMO: # ==================== RESUMO COMPLETO SO2 - TODOS OS COMANDOS ===================='"

    "echo 'RESUMO: # === AULA 2 - COMANDOS BÁSICOS GNU/UNIX ==='"
    "echo 'RESUMO: sudo su → entra como administrador (root)'"
    "echo 'RESUMO: exit ou Ctrl+D → sai do modo root'"
    "echo 'RESUMO: echo \$SHELL → mostra qual shell está usando'"
    "echo 'RESUMO: type <comando> → verifica se é interno, externo ou builtin'"
    "echo 'RESUMO: echo \$PATH → mostra os caminhos de comandos'"
    "echo 'RESUMO: pwd → mostra diretório atual'"
    "echo 'RESUMO: mkdir <pasta> → cria pasta'"
    "echo 'RESUMO: mkdir -p → cria árvore de pastas'"
    "echo 'RESUMO: cd <pasta> → entra na pasta | cd .. → sobe | cd \~ → home | cd - → anterior'"
    "echo 'RESUMO: ls → lista arquivos | ls -a → ocultos | ls -l → detalhado | ls -lh → tamanho legível'"
    "echo 'RESUMO: cat <arquivo> → mostra conteúdo'"
    "echo 'RESUMO: history → mostra histórico | history -c → apaga histórico'"
    "echo 'RESUMO: man <comando> → manual completo | whatis <comando> → descrição curta | <comando> --help → ajuda'"
    "echo 'RESUMO: uname -a → informações do sistema'"
    "echo 'RESUMO: alias → mostra/cria atalhos | unalias → remove atalho'"
    "echo 'RESUMO: !! → repete último comando | !<número> → repete comando do history | Ctrl+R → busca'"
    "echo 'RESUMO: ; → executa comandos em sequência | && → só se sucesso | || → só se falhar'"
    "echo 'RESUMO: setxkbmap -model abnt2 -layout br → teclado ABNT2'"
    "echo 'RESUMO: ./<arquivo> → executa arquivo do diretório atual'"

    "echo 'RESUMO: # === AULA 3 - COMANDOS DE ARQUIVOS DE TEXTO ==='"
    "echo 'RESUMO: nano <arquivo> → editor simples'"
    "echo 'RESUMO: nl <arquivo> → numera linhas'"
    "echo 'RESUMO: cat -n → numerado | cat -b → só linhas com texto | cat -s → reduz linhas em branco | cat -A → mostra caracteres especiais'"
    "echo 'RESUMO: tac <arquivo> → mostra invertido (de baixo para cima)'"
    "echo 'RESUMO: head <arquivo> → primeiras 10 linhas | head -c50 → primeiros 50 bytes'"
    "echo 'RESUMO: tail <arquivo> → últimas linhas | tail -f → acompanha em tempo real'"
    "echo 'RESUMO: less <arquivo> → visualiza paginado (/ = busca, q = sair)'"
    "echo 'RESUMO: wc <arquivo> → linhas, palavras, caracteres | wc -l -w -c'"
    "echo 'RESUMO: sort <arquivo> → ordena | sort -r → inverso | sort -k2 → por coluna'"
    "echo 'RESUMO: uniq → remove duplicadas consecutivas | uniq -c → conta | uniq -d → só duplicadas'"
    "echo 'RESUMO: tr \"a-z\" \"A-Z\" → maiúsculas | tr -d \" \" → apaga espaços | tr -d [:upper:] → apaga maiúsculas'"
    "echo 'RESUMO: fmt -w 50 <arquivo> → formata largura da linha'"
    "echo 'RESUMO: pr -l20 <arquivo> → prepara para impressão'"
    "echo 'RESUMO: cut -c1-5 <arquivo> → recorta caracteres | cut -d: -f1 → recorta por delimitador'"
    "echo 'RESUMO: sed \"s/antigo/novo/g\" <arquivo> → substitui | sed \"/palavra/d\" → apaga linha'"

    "echo 'RESUMO: # === AULA 4 - GERENCIAMENTO DE ARQUIVOS E DIRETÓRIOS ==='"
    "echo 'RESUMO: file <arquivo> → mostra tipo do arquivo'"
    "echo 'RESUMO: cp <origem> <destino> → copia | cp -v -i -p -r → verboso, interativo, preserva, recursivo'"
    "echo 'RESUMO: mv <origem> <destino> → move ou renomeia'"
    "echo 'RESUMO: touch <arquivo> → cria ou atualiza data/hora | touch -t AAAAMMDDHHMM'"
    "echo 'RESUMO: rm <arquivo> → apaga | rm -i -v -r → interativo, verboso, recursivo'"
    "echo 'RESUMO: rmdir <pasta> → apaga pasta vazia'"
    "echo 'RESUMO: find / -name \"*.txt\" → procura arquivo | find -user nome | find -ctime -1'"
    "echo 'RESUMO: tar -cvpf backup.tar * → cria | tar -xvpf → extrai | tar -tvf → lista'"
    "echo 'RESUMO: gzip <arquivo> | gunzip | bzip2 | xz | tar -zcvpf | tar -jcvpf'"
    "echo 'RESUMO: cpio | dd if=... of=... → copia disco/partição'"

    "echo 'RESUMO: # === AULA 5 - REDIRECIONAMENTO E PIPES ==='"
    "echo 'RESUMO: > → sobrescreve saída | >> → adiciona | 2> → erro | 2>> → adiciona erro | &> → tudo'"
    "echo 'RESUMO: 2>&1 → junta erro com saída normal'"
    "echo 'RESUMO: | → pipe (envia saída para outro comando)'"
    "echo 'RESUMO: tee <arquivo> → mostra na tela e salva'"
    "echo 'RESUMO: xargs → passa saída como argumento'"
    "echo 'RESUMO: \`comando\` ou \$(comando) → substituição de comando'"

    "echo 'RESUMO: # === AULA 6/7 - PROCESSOS E PRIORIDADE ==='"
    "echo 'RESUMO: ps auxf | ps -uxaf → lista processos'"
    "echo 'RESUMO: pstree -p → árvore de processos'"
    "echo 'RESUMO: pgrep <nome> → PID por nome'"
    "echo 'RESUMO: top → monitor (Shift+M memória, Shift+C CPU, k matar, q sair)'"
    "echo 'RESUMO: kill <PID> | kill -9 <PID> | kill -s SIGKILL | killall <nome> | pkill <nome>'"
    "echo 'RESUMO: uptime → tempo ligado | free -m → memória | free -g → gigabytes'"
    "echo 'RESUMO: comando & → background | jobs | fg | bg | nohup comando &'"
    "echo 'RESUMO: nice -n -10 comando & → alta prioridade | renice -n 15 -p <PID> → muda prioridade'"

    "echo 'RESUMO: # === AULA 8 - BUSCA COM GREP/REGEX ==='"
    "echo 'RESUMO: grep \"palavra\" <arquivo> | grep -i → ignora maiúscula | grep -r → recursivo | grep -v → exclui'"
    "echo 'RESUMO: grep -c → conta ocorrências'"
    "echo 'RESUMO: egrep \"^Linux|Linux$|b[aeiou]a\" → expressões regulares'"

    "echo 'RESUMO: # === AULA 9 - EDITOR VI/VIM ==='"
    "echo 'RESUMO: vi <arquivo> | vi +18 → abre na linha 18'"
    "echo 'RESUMO: i / I / a / A / o / O → inserir | ESC → modo comando'"
    "echo 'RESUMO: h j k l → mover | dd → apagar linha | yy → copiar | p → colar'"
    "echo 'RESUMO: /texto → buscar | :w → salvar | :wq → salvar e sair | :q! → sair sem salvar'"
    "echo 'RESUMO: :set nu → números de linha | :r <arquivo> → inserir arquivo'"

    "echo 'RESUMO: # === AULA 10 - ARQUITETURA / HARDWARE ==='"
    "echo 'RESUMO: cat /proc/cpuinfo | /proc/meminfo | /proc/interrupts | /proc/ioports | /proc/dma'"
    "echo 'RESUMO: lspci | lsusb | lsblk | blkid | fdisk -l | df -h | dmesg'"
    "echo 'RESUMO: lsmod | modinfo <mod> | insmod | rmmod | modprobe <mod> | modprobe -r'"

    "echo 'RESUMO: # === AULA 11 - BOOT / RUNLEVEL / SYSTEMD ==='"
    "echo 'RESUMO: runlevel → mostra runlevel atual'"
    "echo 'RESUMO: init 0 → desligar | init 6 → reiniciar | telinit'"
    "echo 'RESUMO: systemctl status/start/stop/restart <service>'"
    "echo 'RESUMO: shutdown -r now | shutdown -h now | shutdown -r +10 | reboot | poweroff | halt'"

    "echo 'RESUMO: # === AULA 12/13 - GRUB E MANUTENÇÃO ==='"
    "echo 'RESUMO: update-grub | grub-mkconfig -o /boot/grub/grub.cfg'"
    "echo 'RESUMO: apt-get update | apt-get upgrade | apt-get install | apt-get autoremove | apt-get clean'"
    "echo 'RESUMO: dpkg --configure -a | apt-get install -f | fsck | smartctl -H'"

    "echo 'RESUMO: # === AULA 14 - USUÁRIOS E PERMISSÕES ==='"
    "echo 'RESUMO: adduser <nome> → cria usuário | userdel -r <nome> → remove com pasta'"
    "echo 'RESUMO: usermod -aG sudo <user> → dá privilégio sudo'"
    "echo 'RESUMO: su <user> → troca usuário'"
    "echo 'RESUMO: chmod 755 <arquivo> → permissões (7=rwx, 5=r-x, 4=r--)'"
    "echo 'RESUMO: chown user:grupo <arquivo>'"
    "echo 'RESUMO: passwd | sudo passwd <user> | passwd -l | passwd -u | passwd -d'"
    "echo 'RESUMO: w | finger | less /etc/passwd → usuários'"
)

for cmd in "${COMANDOS[@]}"; do
    history -s "$cmd"
    eval "$cmd"
done

#  chmod +x anot.sh (não usar no modo adm, opcional)
#  source (ou .) anot.sh (coloque espaço antes do comando)
# history | grep "RESUMO"